### ISSUE TITLE
Activated GitHub pages but not working properly

### ISSUE THREAD

**Issue by Shah-Aayush** [ACES-ITNU/website#1]
May be the root directory doesn't have `index.html`.
GH pages link : [https://aces-itnu.github.io/website/](https://aces-itnu.github.io/website/)

**Comment by zeel-codder** [comment]
maybe because of next js. we are going to host on netlify because of the email send API.

**Comment by zeel-codder** [comment]
https://aces-nirma.netlify.app/

**Comment by Shah-Aayush** [comment]
Perfectly done ✅ 
> closing this issue.
